<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>AVATron</AssemblyName>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Skia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AVATron.Core\AVATron.Core.csproj" />
    <ProjectReference Include="..\AVATron.Infrastructure\AVATron.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="AVATron.Tests" />
    <InternalsVisibleTo Include="AVATron.Screenshots" />
  </ItemGroup>
</Project>
